<?php
$entero = 10;                 // Número entero
$decimal = 3.14;              // Número decimal
$cadena = "Hola, PHP";        // Cadena de texto
$booleano = true;             // Booleano (verdadero o falso)
$arreglo = array(1, 2, 3, 4); // Arreglo (array)


echo "Entero: $entero\n";
echo "Decimal: $decimal\n";
echo "Cadena: $cadena\n";
echo "Booleano: " . ($booleano ? 'true' : 'false') . "\n";
echo "Arreglo: ";
print_r($arreglo);
?>
